add a space befor fmt since an error occurred as follows with icx
error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]